### ISSUE TITLE
Make echo'ing the resource to the build logs configurable

### ISSUE THREAD

**Issue by jgriff** [jgriff/k8s-resource#1]
# Background
Currently, `in` will echo the contents of the `resource.json` that was just fetched.  This is very useful for seeing what was retrieved.  However there could be scenarios where this may contain sensitive information you don't want visible from the build logs.

# Agenda
Let's make it a config `param` in the `source`,
```yaml
resources:
  - name: my-k8s-resources
    source:
      sensitive: true
```
This would override the default (`false`) for all `get` steps of the resource.  

We could then also support a param for each `get` to override it per step.
```yaml
jobs:
  - name: view-resources
    plan:
      - get: my-k8s-resources
        version: every
        trigger: true
        params:
          sensitive: false
```
