### ISSUE TITLE
RFC: Wait for cluster conditions on PUT before succeeding

### ISSUE THREAD

**Issue by jgriff** [jgriff/k8s-resource#19]
# Summary

Support (optionally) waiting for cluster resources to meet specific conditions before succeeding from a `put` step.

For example

* create a `Pod` and wait for it to reach `Ready` state. 
* apply a new `Deployment` and then wait for its replicas (or at least 1) to become available.
* ...

Basically, wait for any state you can assert with `jq` expressions against resource(s) retrieved by `check`. 

# Background

Another well-used (but now abandoned) resource type was [`zlabjp/kubernetes-resource`](https://github.com/zlabjp/kubernetes-resource).  It was strictly for `out` operations (no `check` or `get` support).

However, one of its particularly useful features was
[`wait_until_ready`](https://github.com/zlabjp/kubernetes-resource#out-control-the-kubernetes-cluster).
It could periodically poll the target kubernetes cluster and wait for all pods to be in their `Ready` state, with a configurable timeout and label matcher for selecting which pods to assert.
            
https://github.com/zlabjp/kubernetes-resource
```yaml
  - put: k8s-prod
    params:
      kubectl: apply -f my-app/k8s -f my-app/k8s/production
      wait_until_ready: 30 # timeout in seconds (default: 30 seconds)
      wait_until_ready_interval: 3 # check interval in seconds (default: 3 seconds)
      wait_until_ready_selector: app=myapp # label selector for pods (default: all pods in namespace)
```

This was particularly useful for pipelines that applied a new/updated deployment configuration, and wanted to assure the deployment stabilized before moving on.

# Proposal

Support a similar capability, but with the following improvement goals:

* Check _any_ resource (not just pods).
* Use configurable `jq` expression(s) as conditions to assert the desired "wait for" state (not just pod `Ready` state).

For example, to create a new deployment and wait for at least 1 of its replicas to become available:

```yaml
resource_types:
  - name: k8s-resource
    type: docker-image
    source:
      repository: jgriff/k8s-resource

resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))
      namespace: prod

jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx --replicas=3
          await:
            timeout: 120
            resource_types: deployment
            conditions:
              - select(.metadata.name == "my-nginx") | .status.readyReplicas > 0 
```

Waiting after the `put` is triggered/enabled by `await.timeout` having a positive integer value.

The `conditions` are asserted against the collection of resource(s) retrieved by the `check` operation.  
Therefore, you can leverage the `source.filter` support for pre-filtering the resources through your `conditions`.  For example, this would achieve the same result:

```yaml
resource_types:
  - name: k8s-resource
    type: docker-image
    source:
      repository: jgriff/k8s-resource

resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))
      namespace: prod
      resource_types: deployment
      filter:
        name: "my-nginx"

jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx --replicas=3
          await:
            timeout: 120
            conditions:
              - .status.readyReplicas > 0 
```

PROs:
* simplify your `conditions`.
* leverage existing `source.filter` config support.
* remove repetitive `select()` filters from your `conditions`.

CONs:
* splits the configuration across two places (source config and step config).
* could require more than one resource definition for different `put` steps that wish to `await` for different configurations. 

You can mix and match for what makes the most sense in your pipeline, and gives you the DRY-est config.

         
## Configuration

This adds an `await` param to `put` steps with the following attributes:

* `await`: _Optional_.  Configures the `put` to poll `check` for resources and await certain conditions before succeeding using the following criteria: 
  * `timeout`: _Required_.  Must be a positive integer to enable waiting (anything else disables waiting).  Measured in seconds.
  * `conditions`: _Optional_.  List of zero or more `jq` expressions to evaluate.  If none are given, default expressions are inferred based on the `resource_types` being retrieved.
  * `resource_types`: _Optional_.  Overrides the `resources_types` to `check` from the `source` configuration.

No additional `source` configuration will be added.

**Note:** The `put` step already supports overriding the `namespace` as a param.
If you `await` in a `put` step that overrides the `namespace`, that same `namespace` will also be used by `check` to retrieve resources for your `conditions`.  See below for more details. 

### Enablement

To enable waiting, the `put` step must provide a positive integer value for `await.timeout` (in seconds). 

```yaml
- put: k8s
  params:
    kubectl: create deployment my-nginx --image=nginx
    await: 
      timeout: 30 # seconds
```
If `await.timeout` is unset or less than `1`, waiting is disabled.

### What is Polled

Whatever `check` discovers.  That is, this will use the `check` operation to retrieve all of the resources that are then passed to the condition evaluation.
To select which resources you want to wait on, you configure the resource for `check`'ing as usual.

```yaml
resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))
      namespace: prod
      resource_types: deployment
      filter:
        name: "my-nginx"
```

#### Override: Resource Types

You can override the `resource_types` (from the `source` config) that you want to poll and wait for in each individual `put` step. 

```yaml
- put: k8s
  params:
    kubectl: create deployment my-nginx --image=nginx
    await:
      timeout: 30 # seconds
      resource_types: deployment
```

#### Override: Namespaces

Note that `put` already allows you to override the `namespace` as a step param (always has).
This will also be honored by wait in a `put`.  Any `namespace` specified in `put` will also override the namespace used to `check` the resources being waited on.

```yaml
- put: k8s
  params:
    kubectl: create deployment my-nginx --image=nginx
    namespace: prod
    await:
      timeout: 30 # seconds
```

### Wait Conditions

Wait conditions are expressed as `jq` expressions listed under `await.conditions` in the `put` step `params` (similar to the `filter.jq` list in `source` configuration of the resource).

```yaml
- put: k8s
  params:
    kubectl: create deployment my-nginx --image=nginx
    await:
      timeout: 30 # seconds
      conditions:
        - select(.spec.replicas > 0) | .status.readyReplicas > 0
```

* Can list zero or more conditions (see defaults below for when none are given).
* Each expression _must_ evaluate to a boolean result (`true` or `false`), all other results are ignored.
* All conditions must produce at least one `true` result, and no `false` results.
* If the `timeout` is reached before the conditions are satisfied, `put` will fail.

#### Default Conditions

If no `conditions` are given, wait will attempt to infer sensible conditions based on the `resource_types`.
The table below list the conditions that are used by default.

| `resource_types`                          | Default Condition |
| ----------------------------------------- | --------- |
| `pod`, `pods`, `po`                       | <code>select(.kind == "Pod") &#124; .status.containerStatuses[] &#124; .ready</code> | 
| `deployment`, `deployments`, `deploy`     | <code>select(.kind == "Deployment") &#124; select(.spec.replicas > 0) &#124; .spec.replicas == .status.readyReplicas</code> | 
| `replicaset`, `replicasets`, `rs`         | <code>select(.kind == "ReplicaSet") &#124; select(.spec.replicas > 0) &#124; .spec.replicas == .status.readyReplicas</code> | 
| `statefulset`, `statefulsets`, `sts`      | <code>select(.kind == "StatefulSet") &#124; select(.spec.replicas > 0) &#124; .spec.replicas == .status.readyReplicas</code> | 

If multiple `resource_types` are configured (comma-separated), each default condition for that resource type will be added to the overall expression (ie, multiple default conditions) and evaluated together.  

For example, this:

```yaml
resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))
      resource_types: pod,deployment
      namespace: prod
jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx
          await: 
            timeout: 30 # seconds
```

is equivalent to:

```yaml
resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))
      resource_types: pod,deployment
      namespace: prod
jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx
          await: 
            timeout: 30 # seconds
            conditions:
              - select(.kind == "Pod") | .status.containerStatuses[] | .ready 
              - select(.kind == "Deployment") | select(.spec.replicas > 0) | .status.readyReplicas > 0
```        

### All Defaults
                              
Below is the most minimal configuration, omitting all optional configuration and using all defaults.
It will wait at most 30 seconds for _all_ pods in `--all-namespaces` to become `Ready`.

```yaml
---
resource_types:
  - name: k8s-resource
    type: docker-image
    source:
      repository: jgriff/k8s-resource

resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))

jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx
          await: 
            timeout: 30 # seconds
            
```

* Waiting enabled since an `await.timeout` was specified (by default, there is no waiting).
* Polls `--all-namespaces` since that is the default for `namespace` in the `source` config.
* Polls for `pods` resources since that is the default for `resource_types` in the `source` config.
* Waits for condition `select(.kind == "Pod") | .status.containerStatuses[] | .ready` since that is the default condition for `pods` resources.

### Leveraging `check` filters 

Here we can leverage our existing `source.filter` criteria to narrow down what we're waiting for, and simplify our `await` configuration.

```yaml
---
resource_types:
  - name: k8s-resource
    type: docker-image
    source:
      repository: jgriff/k8s-resource

resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))
      namespace: prod
      resource_types: deployment
      filter:
        name: "my-nginx"

jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx
          await:
            timeout: 120 
```
              
* Waits at most 2 minutes (120 seconds).
* Polls the `prod` namespace since that is the configured `namespace` in the `source` config.
* Polls for `deployment` resources since that is the configured `resource_types` in the `source` config.
* Filters the deployments for only the one named `"my-nginx"` (will be deployed by the `put` step).
* Uses the default condition for `deployment` resources, which waits for at least 1 replica to become available.

### Full Expressed `put`

Here is the same example as above, but fully configured in the `put` step instead of leveraging the `source` filter configuration.

```yaml
---
resource_types:
  - name: k8s-resource
    type: docker-image
    source:
      repository: jgriff/k8s-resource

resources:
  - name: k8s
    type: k8s-resource
    icon: kubernetes
    source:
      url: ((k8s-server))
      token: ((k8s-token))
      certificate_authority: ((k8s-ca))

jobs:
  - name: deploy-nginx
    plan:
      - put: k8s
        params:
          kubectl: create deployment my-nginx --image=nginx
          namespace: prod
          await:
            timeout: 120
            resource_types: deployment
            conditions:
              - select(.metadata.name == "my-nginx") | .status.readyReplicas > 0 
```

The advantage of this approach is you can reuse the `k8s` resource for other `put` steps and configure the `await` to wait for different types of resources, in different namespaces.
