### ISSUE TITLE
Support namespace in source config

### ISSUE THREAD

**Issue by jgriff** [jgriff/k8s-resource#2]
# Background

Currently, `check` queries `--all-namespaces`.  

# Agenda

Support configuring a particular namespace to narrow the `check` to.

```yaml
resources:
  - name: my-k8s-resources
    source:
      namespace: my-namespace
```
