### ISSUE TITLE
RFC: Filter by metadata labels

### ISSUE THREAD

**Issue by jgriff** [jgriff/k8s-resource#21]
# Summary

Add support for [filtering resources with a `--selector`](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) (ie, metadata labels).

This would add a new `selector` option to the source `filter` configuration:

```yaml
source:
  filter:
    selector: app=my-app
```

Any valid value for `kubectl`'s `--selector` option can be specified here, including equality (`=`, `==`, `!=`) and set-based requirements (`in (...)`, `notin (...)`).

### Single Label Match
```yaml
source:
  filter:
    selector: environment=production
```

### Multiple Label Match
```yaml
source:
  filter:
    selector: environment=production,tier=frontend
```

### Set-based Requirements
```yaml
source:
  filter:
    selector: environment in (development,production),tier in (frontend)
```

### Negative Matches
```yaml
source:
  filter:
    selector: environment!=production
```

```yaml
source:
  filter:
    selector: environment,environment notin (production)
```

### Combining Styles
```yaml
source:
  filter:
    selector: environment=production,tier in (frontend,backend) 
```
