### ISSUE TITLE
Complex k8s metadata in the version confuses Concourse

### ISSUE THREAD

**Issue by jgriff** [jgriff/k8s-resource#3]
# Background

Currently, `in` will include all `metadata {}` elements from the k8s resource as `metadata {}` elements in the emitted version.

Kubernetes `metadata` can contain complex structures.  For example,

```yaml
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"my-app\"},\"name\":\"my-app-system\"}} "
    }
  }
```

This blows up Concourse, which expects _only_ simple strings for values.

# Agenda

Filter the `metadata` we absorb into the version to only those keys which have simple string values.  Discard all non-string value keys.
