### ISSUE TITLE
Patch deployment fails due to resource type

### ISSUE THREAD

**Issue by Aqualie** [jgriff/k8s-resource#31]
When using patch deployment an error is returned regarding duplicate resource type:

pipeline configuration:
```
resources:
resource_types:
  - name: k8s-resource
    type: docker-image
    source:
      repository: jgriff/k8s-resource
- name: k8s
  type: k8s-resource
  icon: kubernetes 
  source:
    url: REPLACED
    token: {{K8S_TOKEN}}
    certificate_authority: {{K8S_CA}}
    namespace: REPLACED

    - put: k8s
      params:
        kubectl: patch deployments.app REPLACED -p '{"spec":{"template":{"spec":{"containers":[{"name":"REPLACED ","image":"REPLACED :'$(cat version/version)'"}]}}}}' 
        await:
          timeout: 300
```

concourse output:
```
Output:
--> Invoking kubectl with args patch deployments.app REPLACED -p '{"spec":{"template":{"spec":{"containers":[{"name":"REPLACED","image":"REPLACED:'$(cat version/version)'"}]}}}}' targeting cluster at https://REPLACED:6443 in namespace REPLACED...
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'
```

**Comment by jgriff** [comment]
This looks like a compound issue between:

1. How finicky `kubectl` and the server are with inline patches (ie, specified on one line with `-p {}`).
2. How our resource treats the `kubectl` param value when it comes to string literals and escape characters.

The error is really due to munging the patch JSON, and confusing the `kubectl` request.

## Workaround

I was able to get your example to work by using a step to write the patch to a file, then using `--patch-file` instead of the inline patch `-p`.

```yaml
      - task: create-patches
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          outputs:
            - name: patches
          run:
            path: sh
            args:
              - -exc
              - |
                echo '{"spec":{"template":{"spec":{"containers":[{"name":"REPLACED","image":"REPLACED"}]}}}}' >> patches/patch.yaml
      - put: k8s
        params:
          kubectl: patch deployment REPLACED --patch-file=patches/patch.yaml
          await:
            timeout: 300
```
