### ISSUE TITLE
Initial 'out' support with simple kubectl command

### ISSUE THREAD

**Issue by jgriff** [jgriff/k8s-resource#7]
# Background

Currently, this resource does not (yet) support `out`.  

But now that we have basic `check` and `in` operations, we can move over to supporting the outbound side with a rudimentary `out` that can simply execute a `kubectl` command (provided as a `params` to the `put` step).

# Agenda

Add first pass support for configuring a `put` step, where the user configures the args to pass to `kubectl`.

Since the user declares everything that is passed to `kubectl`, this would immediately open a wide range of usages.

## Examples

Apply a single resource file.
```yaml
      - get: my-resources-repo
      - put: deploy-pod
        resource: k8s-resource
        params:
          kubectl: apply -f my-resources/some-resource.yaml
```

Apply a [kustomization](https://kustomize.io) overlay.
```yaml
      - get: my-resources-repo
      - put: deploy-overlay
        resource: k8s-resource
        params:
          kubectl: apply -k my-resources/overlays/prod
```

Delete stuff.
```yaml
      - put: delete-something
        resource: k8s-resource
        params:
          kubectl: apply delete pod my-pod
```

yadda yadda

## Implied Args

The `kubectl` command will be prefixed with the necessary args from the `source` configuration.

```shell
kubectl --server=$source_url --token=$source_token --certificate-authority=$source_ca_file
```

## Parameters

Initially, we'll want to support the following parameters for `out`:

* `kubectl` - _Required_ (obviously).  All of the args to pass directly to `kubectl`.
* `namespace` - _Optional_.  Defaults to the `source.namespace` configuration.  If that is not configured either, then `default` is used.

## Output

Since a strict version output won't make sense for all `put` uses, the output emitted by `out` should just indicate the command that was run.  This will be handy when viewing the pipeline in the UI.

```yaml
{
  "version": { "kubectl": "<the command that was run>" }
}
```

If any `metadata` turns out to make sense, emit that too.
